project:
  type: book
  output-dir: docs

book:
  title: "Sandbox Notebook Rendering"
  author: "Simon Worthington"
  date: "2023-04-14"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - paintings.ipynb
    - collection_1_template.ipynb
    - collection_1_sprengel.ipynb
    - collection_1_ahmad.ipynb
    - collection_1_albaloush.ipynb
    - collection_1_aroud.ipynb
    - collection_1_cornelius.ipynb
    - collection_1_darkhabani.ipynb
    - collection_1_debase.ipynb
    - collection_1_kromm.ipynb
    - collection_1_sommer.ipynb
    - collection_1_tuku.ipynb
    - references.qmd
repo-url: https://github.com/NFDI4Culture/sandbox-notebook-rendering
repo-actions: [edit]
downloads: [pdf,epub,docx]
cover-image: cover/Hybrid_European_RF_and_Antenna_Test_Zone_sml.jpg
bibliography: references.bib

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at https://quarto.org/docs/output-formats/html-themes.html
    theme: journal
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  pdf:
    documentclass: book
  docx:   
    toc: true
  epub:   
    toc: true







